Repository Pick-and-buy/UGTS-Back-stage, pull requests merged in 2024-07, with the labels that each got.

#64 Feat/vnpay service
  src/main/java/com/ugts/configuration/SecurityConfig.java
  src/main/java/com/ugts/order/dto/response/OrderDetailsResponse.java
  src/main/java/com/ugts/order/entity/OrderDetails.java
  src/main/java/com/ugts/order/service/impl/OrderServiceImpl.java
  src/main/java/com/ugts/transaction/entity/Transaction.java
  src/main/java/com/ugts/transaction/repository/TransactionRepository.java
  src/main/java/com/ugts/transaction/service/impl/TransactionServiceImpl.java
  src/main/java/com/ugts/user/repository/AddressRepository.java
  src/main/java/com/ugts/vnpay/configuration/VnPayConfiguration.java
  src/main/java/com/ugts/vnpay/controller/VNPayController.java
  src/main/java/com/ugts/vnpay/dto/request/CreateVNPayRequest.java
  src/main/java/com/ugts/vnpay/service/VNPayService.java
  src/main/java/com/ugts/vnpay/service/impl/VNPayServiceImpl.java
Labels: enhancement

#65 feat(category): fix bug #63 delete category api
  src/main/java/com/ugts/category/controller/CategoryController.java
  src/main/java/com/ugts/category/entity/Category.java
  src/main/java/com/ugts/category/service/CategoryService.java
  src/main/java/com/ugts/category/service/impl/CategoryServiceImpl.java
Labels: closed, resolved

#71 bugfix(order): update logic of update order status
  src/main/java/com/ugts/order/service/impl/OrderServiceImpl.java
Labels: resolved

#72 bugfix(address): fix cascade type between address and user
  src/main/java/com/ugts/user/entity/User.java
Labels: resolved

#76 bugfix(order): fixed order address
  src/main/java/com/ugts/order/dto/request/CreateOrderRequest.java
  src/main/java/com/ugts/order/dto/response/OrderDetailsResponse.java
  src/main/java/com/ugts/order/service/impl/OrderServiceImpl.java
  src/main/java/com/ugts/user/repository/AddressRepository.java
  src/main/resources/application.properties
Labels: resolved

#79 feat(brand): add pagination for brand
  src/main/java/com/ugts/brand/controller/BrandController.java
  src/main/java/com/ugts/brand/repository/BrandRepository.java
  src/main/java/com/ugts/order/dto/response/OrderDetailsResponse.java
  src/main/java/com/ugts/post/controller/PostController.java
  src/main/java/com/ugts/post/dto/request/UpdatePostRequest.java
  src/main/java/com/ugts/post/service/IPostService.java
  src/main/java/com/ugts/post/service/impl/PostServiceImpl.java
  src/main/java/com/ugts/user/controller/UserController.java
  src/main/java/com/ugts/user/service/impl/UserServiceImpl.java
Labels: enhancement

#80 Feat/notification
  .DS_Store
  docker-compose.yml
  pom.xml
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/com/ugts/UseGoodTradingSystemApplication.java
  src/main/java/com/ugts/comment/service/impl/CommentServiceImpl.java
  src/main/java/com/ugts/configuration/FireBaseConfiguration.java
  src/main/java/com/ugts/constant/AppConstant.java
  src/main/java/com/ugts/exception/ErrorCode.java
  src/main/java/com/ugts/follow/service/FollowServiceImpl.java
  src/main/java/com/ugts/kafka/config/KafkaTopicConfig.java
  src/main/java/com/ugts/kafka/consumer/KafkaConsumer.java
  src/main/java/com/ugts/kafka/producer/KafkaProducer.java
  src/main/java/com/ugts/notification/controller/NotificationController.java
  src/main/java/com/ugts/notification/controller/PushNotificationController.java
  src/main/java/com/ugts/notification/dto/NotificationResponse.java
  src/main/java/com/ugts/notification/entity/NotificationEntity.java
  src/main/java/com/ugts/notification/entity/NotificationType.java
  src/main/java/com/ugts/notification/mapper/NotificationMapper.java
  src/main/java/com/ugts/notification/repository/NotificationRepository.java
  src/main/java/com/ugts/notification/service/INotificationService.java
  src/main/java/com/ugts/notification/service/NotificationServiceImpl.java
  src/main/java/com/ugts/notification/service/PushNotificationService.java
  src/main/java/com/ugts/user/entity/User.java
  src/main/java/com/ugts/user/service/impl/UserServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement
